#!/bin/bash

TIME=5
command='mvn clean install'

###################################

if [ $# -gt 0 ]; then 
    command="$command $@"
fi

$command

if [ $? == 0 ]; then
    status="BUILD SUCCESS"
else
    status="BUILD FAILED"
fi

echo -e "\a"
msg $(whoami) /TIME:$TIME "$status:     $(basename "$PWD")"
